[package]
name = "database"
version = "0.1.0"
edition = "2021"

[lib]
name = "database"
path = "src/lib.rs"

[dependencies]
eyre.workspace = true

common = { path = "../common" }
config = { path = "../config" }